
couchbase:
  image: betagouv/api-meds-db
  hostname: couchbase.meds
  container_name: couchbase.meds
  ports:
    - 8091-8094:8091-8094
    - 11210:11210

api:
  image: betagouv/api-meds-api
  environment:
    cb_connectionString: couchbase://couchbase.meds:8091
  links:
    - couchbase:couchbase.meds
  hostname: api.med
  container_name: api.med
  ports:
    - 3004:3004
