version: '2'

networks:
  cbNetwork:
    driver: bridge

services:
  couchbase:
    image: couchbase:community
    hostname: couchbase.meds
    container_name: couchbase.meds
    networks:
      - cbNetwork
    ports:
      - 8091-8094:8091-8094
      - 11210:11210
    volumes:
      - ./cbData:/opt/couchbase/var/lib/couchbase/data

  configuration:
    image: couchbase:community
    networks:
      - cbNetwork
    depends_on:
      - couchbase
    container_name: config
    volumes:
      - ./bin/prepareDataBase.sh:/opt/couchbase/bin/cb-config.sh
    hostname: config
    #command: ping couchbase.meds
    command: bash /opt/couchbase/bin/cb-config.sh couchbase.meds admin tototiti
